### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by paulinofonsecas** [CarloDotLog/mason_bricks#6]
![image](https://github.com/user-attachments/assets/b2eb0432-24a3-4566-a6a9-bf1d9e2e71f9)

**Comment by CarloDotLog** [comment]
Thank you for your issue. I fixed it and uploaded the new version on brickhub.dev.

You can check it here https://brickhub.dev/bricks/clean_architecture_folders/0.1.1+4

**Comment by paulinofonsecas** [comment]
Thanks for your attention
